export enum APP_TYPES {
	CHANGE_CURRENT_USER = "APP.CHANGE_CURRENT_USER",
}

export enum SIGN_IN_TYPES {
	START_SIGN_IN = "SIGN_IN.START_SIGN_IN",
	SUCCEEDED_SIGN_IN = "SIGN_IN.SUCCEEDED_SIGN_IN",
	FAILED_SIGN_IN = "SIGN_IN.FAILED_SIGN_IN",
}
