name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["10.x"]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm install

      - name: Test
        run: |
          npm test
        env:
          CI: true

      - name: Deploy to Production
        uses: actions/heroku@master
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        secrets: [${{ secrets.HEROKU_API_KEY }}]
        run: |
          ls -al
          heroku apps
